<script lang="ts">
  import Markdown from './Markdown.svelte';
  import type { Citation, CustomSectionPlacement, ReportViewModel } from './types';
  let { report, onSource, onSelect }: { report: ReportViewModel; onSource: (id: string) => void; onSelect: (id: string) => void } = $props();
  const cross = $derived(report.analysis.crossThread);
  function number(value: number): string { return new Intl.NumberFormat().format(value); }
  function duration(value: number): string { if (value < 60) return `${Math.round(value)}s`; if (value < 3600) return `${Math.round(value / 60)}m`; return `${Math.floor(value / 3600)}h ${Math.round((value % 3600) / 60)}m`; }
  function source(citation: Citation) { onSource(citation.evidenceId); }
  function slots(placement: CustomSectionPlacement) { return (report.analysis.customSections || []).filter((slot) => slot.placement === placement && !slot.sessionId); }
</script>
<main class="case-file analysis-page">
  <header class="case-header"><span class="kicker">Run-wide findings</span><h1>Cross-thread analysis</h1><p class="page-intro">Patterns and outcomes that only become visible when the workstreams are read together.</p></header>
  <section class="cross-thread-section"><Markdown content={cross.summary || cross.outcomeSynthesis} />
    {#if cross.outcomeSynthesis}<div class="analysis-summary"><span class="kicker">Overall outcome</span><Markdown content={cross.outcomeSynthesis} /></div>{/if}
    {#if cross.outcomeMatrix.length}<h2>Outcome matrix</h2><div class="outcome-matrix" role="table"><div class="matrix-header" role="row"><span>Objective</span><span>Workstreams</span><span>Result</span><span>Remaining risk</span></div>{#each cross.outcomeMatrix as row}<div class="matrix-row" role="row"><strong>{row.objective}</strong><span>{#each row.sessionIds as id}<button onclick={() => onSelect(id)}>{report.byId.get(id)?.label || id.slice(-8)}</button>{/each}</span><span>{row.result}</span><span>{row.remainingRisk}</span></div>{/each}</div>{/if}
    {#if cross.failureThemes.length}<h2>Common failure themes</h2><div class="theme-list">{#each cross.failureThemes as theme}<article><h3>{theme.title}</h3><Markdown content={theme.summary} /><p>{theme.affectedSessionIds.length} affected workstreams</p><div class="citation-row">{#each theme.citations as citation}<button onclick={() => source(citation)}>Source</button>{/each}</div></article>{/each}</div>{/if}
    <div class="analysis-columns"><article><h2>Delegation effectiveness</h2><Markdown content={cross.delegationEffectiveness || 'Not analyzed.'} /></article><article><h2>Resource distribution</h2><Markdown content={cross.resourceInterpretation || 'Not analyzed.'} /><dl class="resource-stats"><div><dt>Recorded elapsed</dt><dd>Total {duration(report.resourceStatistics.duration.total)} · mean {duration(report.resourceStatistics.duration.mean)} · median {duration(report.resourceStatistics.duration.median)} · range {duration(report.resourceStatistics.duration.min)}–{duration(report.resourceStatistics.duration.max)} · {report.resourceStatistics.duration.count}/{report.workstreams.length} recorded</dd></div><div><dt>Tool calls</dt><dd>Total {number(report.resourceStatistics.toolCalls.total)} · mean {number(Math.round(report.resourceStatistics.toolCalls.mean))} · median {number(report.resourceStatistics.toolCalls.median)} · range {number(report.resourceStatistics.toolCalls.min)}–{number(report.resourceStatistics.toolCalls.max)} · {report.resourceStatistics.toolCalls.count}/{report.workstreams.length} recorded</dd></div><div><dt>Detected related-session tokens</dt><dd>Total {number(report.resourceStatistics.tokens.total)} · mean {number(Math.round(report.resourceStatistics.tokens.mean))} · median {number(report.resourceStatistics.tokens.median)} · range {number(report.resourceStatistics.tokens.min)}–{number(report.resourceStatistics.tokens.max)} · {report.resourceStatistics.tokens.count}/{report.workstreams.length} recorded</dd></div></dl></article></div>
    {#if report.modelStatistics.length}<h2>Attributed tokens by model</h2><p class="section-note">Cumulative counter deltas are assigned to the model active at each captured token snapshot. This is usage detected in the related sessions, not account-wide billing.</p><div class="model-usage" role="table" aria-label="Attributed token usage by model"><div class="model-usage-header" role="row"><span>Model</span><span>Sessions</span><span>Effort</span><span>Total tokens</span><span>Uncached input</span><span>Output</span><span>Reasoning</span></div>{#each report.modelStatistics as usage}<div class="model-usage-row" role="row"><strong>{usage.model}</strong><details><summary>{usage.sessionIds.length}</summary>{#each usage.sessionIds as id}<button onclick={() => onSelect(id)}>{report.byId.get(id)?.label || id.slice(-8)}</button>{/each}</details><span>{usage.efforts.join(', ') || 'Not recorded'}</span><span>{number(usage.total || 0)}</span><span>{number(usage.uncachedInput || 0)}</span><span>{number(usage.output || 0)}</span><span>{number(usage.reasoning || 0)}</span></div>{/each}</div>{/if}
  </section>
  {#each slots('cross-thread-after-core') as slot (slot.id)}{@const Section = slot.component}<Section {report} evidence={report.evidence} />{/each}
  {#each slots('root-after-cross-thread') as slot (slot.id)}{@const Section = slot.component}<Section {report} evidence={report.evidence} />{/each}
</main>
